// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./../src/layout/components/header/ActionBar.vue')['default']
    AppProvider: typeof import('./../src/components/AppProvider/AppProvider.vue')['default']
    Avatar: typeof import('./../src/layout/components/header/Avatar.vue')['default']
    BaseLayout: typeof import('./../src/layout/BaseLayout.vue')['default']
    BasicForm: typeof import('./../src/components/Form/BasicForm.vue')['default']
    BasicModal: typeof import('./../src/components/Modal/BasicModal.vue')['default']
    DragVerify: typeof import('./../src/components/DragVerify/DragVerify.vue')['default']
    Header: typeof import('./../src/layout/components/header/Header.vue')['default']
    Logo: typeof import('./../src/layout/components/logo/Logo.vue')['default']
    Menu: typeof import('./../src/layout/components/menu/Menu.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NTooltip: typeof import('naive-ui')['NTooltip']
    StandardLayout: typeof import('./../src/layout/StandardLayout.vue')['default']
  }
}

export { }
